### PR TITLE
new simple_html_dom.php

### PR DESCRIPTION
**Pull request by MegaphoneJon**
I tried this extension today and it wasn't working - the "simple_html_dom" library is old enough that the regex is for the old PHP regex engine.  So it couldn't parse the HTML to find the stylesheet.  I found the latest version in the 1.x series and dropped it in, and lo and behold, the extension started working.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
cool

**Comment by eileenmcnaughton** [comment]
Oddly enough look at the release history

image


Should I tag another?

**Comment by MegaphoneJon** [comment]
@eileenmcnaughton I think so - I'm not sure how this is working for anyone, since the pre-today version shouldn't be working on any flavor of PHP 7

**Comment by eileenmcnaughton** [comment]
@jackrabbithanna that last PR was from you - did you use the extension at all - or just try to get it woring?

**Comment by jackrabbithanna** [comment]
No, was just trying to fix that PHP deprecation warning. Was on a dev site for a D9 upgrade. Making a task in our queue now to test.

**Comment by jackrabbithanna** [comment]
Definitely the new tag works, 1.2 failed in testing. 
We still see this:
Notice: Trying to access array offset on value of type int in csstidy_optimise->merge_4value_shorthands() (line 615 of /home/vagrant/drupal7/sites/default/files/civicrm/ext/nz.co.fuzion.cssinline-master/packages/cssin/vendor/csstidy/class.csstidy_optimise.php).
Notice: Trying to access array offset on value of type int in csstidy_optimise->merge_4value_shorthands() (line 615 of /home/vagrant/drupal7/sites/default/files/civicrm/ext/nz.co.fuzion.cssinline-master/packages/cssin/vendor/csstidy/class.csstidy_optimise.php).
I think we need to use latest version of library : https://github.com/Cerdic/CSSTidy/blob/master/class.csstidy_optimise.php#L688

**Comment by eileenmcnaughton** [comment]
@jackrabbithanna @MegaphoneJon - I'm not hugely vested in this library - if one of you cares enough to put up a PR to do the update per ^^ I'll merge it & put out a new release

**Pull request merged**
